### ISSUE TITLE
Find a better way to test humpty

### ISSUE THREAD

**Issue by Munksgaard** [Manishearth/humpty_dumpty#6]
Something like rustc's compiletest would be nice to have.

cc @laumann

**Comment by Manishearth** [comment]
I've been poking people to move compiletest to a separate crate for a while; but it's hard.

We could write a minimal version of it or just try to extract it and see what happens.

**Comment by Munksgaard** [comment]
I think @laumann is working on extracting at least some of compiletests functionality into a separate library. We'll see how it goes :)

**Comment by Munksgaard** [comment]
Heres a start :) https://github.com/laumann/compiletest-rs

**Comment by Manishearth** [comment]
Wow, compiletest looks awesome! :D
